version: '3.9'

services:
  app:
    build:
      context: ./php
    container_name: pyrhonLerningApp
    volumes:
      - ./src:/var/www/html
    # host : container
    ports:
      - "8085:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
