version: '3.8'

services:
  app:
    build: .
    container_name: pythonLerningApp
    ports:
      - "8099:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1a24c3de
      MYSQL_DATABASE: laravel
      MYSQL_USER: marimo
      MYSQL_PASSWORD: 1a24c3de1a24c3de
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
